#:schema node_modules/wrangler/config-schema.json
name = "buscamos-casa-site"
compatibility_date = "2024-12-28"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_flags = ["nodejs_compat"]


d1_databases = [
    { binding = "DB", database_name = "bc-db-dev", database_id = "f564a774-9a08-48eb-a5ca-e13e35011b7c", preview_database_id = "DB", migrations_dir = "drizzle" },
]
kv_namespaces = [
    { binding = "CACHE_KV", id = "fe38d90fef3b4279a1437b1f8566e6ce", preview_id = "fe38d90fef3b4279a1437b1f8566e6ce"}, 
]


[env.preview]
d1_databases = [
    { binding = "DB", database_name = "bc-db-preview", database_id = "11d0a4bd-636c-4ac5-b3a7-45a4b88a0300", preview_database_id = "DB", migrations_dir = "drizzle" },
]
kv_namespaces = [
    { binding = "CACHE_KV", id = "e9b3508001614d2589db26eda5e171eb", preview_id = "e9b3508001614d2589db26eda5e171eb"}, 
]


[env.production]
d1_databases = [
    { binding = "DB", database_name = "bc-db-prod", database_id = "334c7c99-7bf1-4c19-9384-3528980b0ba3", preview_database_id = "DB", migrations_dir = "drizzle" },
]
kv_namespaces = [
    { binding = "CACHE_KV", id = "8997438e91f34f4dbd7c60e03488bb55", preview_id = "8997438e91f34f4dbd7c60e03488bb55"}, 
]