#:schema node_modules/wrangler/config-schema.json
name = "buscamos-casa-site"
compatibility_date = "2024-12-28"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_flags = ["nodejs_compat"]


d1_databases = [
    { binding = "DB", database_name = "bc-db-development", database_id = "67fb6cb4-15ef-4924-b495-f65e3a9a61e2", preview_database_id = "DB", migrations_dir = "drizzle" },
]


[env.preview]
d1_databases = [
    { binding = "DB", database_name = "bc-db-preview", database_id = "11d0a4bd-636c-4ac5-b3a7-45a4b88a0300", preview_database_id = "DB", migrations_dir = "drizzle" },
]


[env.production]
d1_databases = [
    { binding = "DB", database_name = "bc-db-prod", database_id = "334c7c99-7bf1-4c19-9384-3528980b0ba3", preview_database_id = "DB", migrations_dir = "drizzle" },
]
