#:schema node_modules/wrangler/config-schema.json
name = "buscamos-casa-site"
compatibility_date = "2024-12-28"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_flags = ["nodejs_compat"]

d1_databases = [
    { binding = "DB", database_name = "bc-db-dev", database_id = "dc4ed84f-f098-4ff3-a2b8-c58ff28a35f2", preview_database_id = "DB", migrations_dir = "drizzle" },
]
kv_namespaces = [
    { binding = "CACHE_KV", id = "fe38d90fef3b4279a1437b1f8566e6ce", preview_id = "fe38d90fef3b4279a1437b1f8566e6ce"}, 
]


[env.preview]
d1_databases = [
    { binding = "DB", database_name = "bc-db-preview", database_id = "a77ccd8e-fec2-41cd-ae9f-4d5ddbec0ccf", preview_database_id = "DB", migrations_dir = "drizzle" },
]
kv_namespaces = [
    { binding = "CACHE_KV", id = "e9b3508001614d2589db26eda5e171eb", preview_id = "e9b3508001614d2589db26eda5e171eb"}, 
]


[env.production]
d1_databases = [
    { binding = "DB", database_name = "bc-db-prod", database_id = "cfb3b0f4-08a8-4055-8120-85f465eb0aee", preview_database_id = "DB", migrations_dir = "drizzle" },
]
kv_namespaces = [
    { binding = "CACHE_KV", id = "8997438e91f34f4dbd7c60e03488bb55", preview_id = "8997438e91f34f4dbd7c60e03488bb55"}, 
]