ALTER TABLE `property_financial_details`
ADD COLUMN `maintenance_cost` real;

INSERT INTO features (name) VALUES
('Acceso para discapacitados'),
('Aire acondicionado'),
('Alarma contra incendios'),
('Antejardín'),
('Área de BBQ'),
('Área Social'),
('Baño de visitas'),
('Balcón'),
('Bar'),
('Bodega'),
('Calle sin salida'),
('Calefacción'),
('Cancha de baloncesto'),
('Cancha de futbol'),
('Cancha de tenis'),
('Cancha de pádel'),
('Carga para vehículos eléctricos'),
('Casa club'),
('Chimenea'),
('Cerca de Escuela'),
('Cerca del Tráfico'),
('Cerca de supermercado'),
('Cerradura inteligente'),
('Cine'),
('Cocina abierta'),
('Cocina amoblada'),
('Comedor de diario'),
('Conserjería'),
('Cuarto y baño de empleado'),
('Depósito'),
('Desayunador'),
('Despensa'),
('Elevador'),
('En Condominio'),
('Frente al Lago'),
('Frente al Mar'),
('Frente al Río'),
('Garaje techado'),
('Gimnasio'),
('Jacuzzi'),
('Jardín'),
('Lavandería interna'),
('Lobby'),
('Oficina'),
('Parque Infantil'),
('Parque para Mascotas'),
('Parqueo bajo techo'),
('Parqueo de visitas'),
('Patio lateral'),
('Patio trasero'),
('Pet Friendly'),
('Piscina'),
('Planta Eléctrica'),
('Portón eléctrico'),
('Riego automático'),
('Sala y Comedor'),
('Salón de fiestas'),
('Seguridad 24 Horas'),
('Sistema de alarma'),
('Terraza'),
('Terreno en esquina'),
('Vista a las Montañas'),
('Vista al Lago'),
('Vista al Mar'),
('Walk-in closet');
